service: confirmation-operations
useDotenv: true

custom:
  stage: ${opt:stage, 'local'}
  resourcesBaseName: ${self:service}-resources-${self:provider.stage}
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
  lambdaHashingVersion: 20201221
  lambda:
    mountCode: true
  pythonRequirements:
    zip: false
    pip: true
    slim: true
    strip: false

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  endpointType: REGIONAL
  profile: ${opt:stage, 'dev'}
  stage: ${opt:stage, 'dev'}
  environment:
    REGION_NAME: ${self:provider.region}
    SECRET_NAME: ${cf:${self:custom.resourcesBaseName}.DatabaseSecretArn}
    SFTP_SERVER_SECRET: ${cf:${self:custom.resourcesBaseName}.SftpServerSecretArn}
    BUCKET_NAME: ${cf:${self:custom.resourcesBaseName}.ProcesamientoBucketName}
    QUEUE_NAME: ${cf:${self:custom.resourcesBaseName}.OutputQueueUrl}

plugins:
  - serverless-python-requirements
  - serverless-step-functions
  - serverless-localstack

package:
  individually: true

functions:
  TriggerStepFunction:
    handler: src/functions/trigger_step_function.handler
    environment:
      STEP_FUNCTION_ARN: arn:aws:states:${self:provider.region}:${aws:accountId}:stateMachine:${self:service}-${self:provider.stage}-procesamiento-state-machine
    events:
      - sqs:
          arn: ${cf:${self:custom.resourcesBaseName}.InputQueueArn}
          batchSize: 1
    package:
      include:
        - src/utils/logger.py
        - src/functions/trigger_step_function.py
  ValidarCliente:
    handler: src/functions/validar_cliente.handler
    role: !GetAtt ValidarClienteRole.Arn
    environment:
      SECRET_NAME: ${cf:${self:custom.resourcesBaseName}.DatabaseSecretArn}
    package:
      include:
        - src/utils/**
        - src/services/**
        - src/functions/validar_cliente.py
  ValidarFechas:
    handler: src/functions/validar_fechas.handler
    package:
      include:
        - src/utils/**
        - src/functions/validar_fechas.py
  ValidarMoneda:
    handler: src/functions/validar_moneda.handler
    package:
      include:
        - src/utils/logger.py
        - src/functions/validar_moneda.py
  GenerarXML:
    handler: src/functions/generar_xml.handler
    role: !GetAtt GenerarXMLRole.Arn
    environment:
      BUCKET_NAME: ${cf:${self:custom.resourcesBaseName}.ProcesamientoBucketName}
    package:
      include:
        - src/utils/**
        - src/services/**
        - src/functions/generar_xml.py
  EnviarResultado:
    handler: src/functions/enviar_resultado.handler
    role: !GetAtt EnviarResultadoRole.Arn
    environment:
      OUTPUT_QUEUE_URL: ${cf:${self:custom.resourcesBaseName}.OutputQueueUrl}
    package:
      include:
        - src/utils/logger.py
        - src/functions/enviar_resultado.py
  EnviarCorreo:
    handler: src/functions/enviar_correo.handler
    package:
      include:
        - src/utils/logger.py
        - src/functions/enviar_correo.py
  CopiarSFTP:
    handler: src/functions/copiar_sftp.handler
    role: !GetAtt GenerarXMLRole.Arn
    environment:
      BUCKET_NAME: ${cf:${self:custom.resourcesBaseName}.ProcesamientoBucketName}
      SFTP_SERVER_SECRET: ${cf:${self:custom.resourcesBaseName}.SftpServerSecretArn}
    package:
      include:
        - src/utils/**
        - src/services/**
        - src/functions/copiar_sftp.py

resources:
  Resources:
    ValidarClienteRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-validar-cliente-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${self:provider.stage}-validar-cliente-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource: ${cf:${self:custom.resourcesBaseName}.DatabaseSecretArn}
    GenerarXMLRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-generar-xml-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${self:provider.stage}-generar-xml-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:ListBucket
                    - s3:PutObject
                  Resource: ${cf:${self:custom.resourcesBaseName}.ProcesamientoBucketArn}
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource: ${cf:${self:custom.resourcesBaseName}.DatabaseSecretArn}
    EnviarResultadoRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-enviar-resultado-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${self:provider.stage}-enviar-resultado-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource: ${cf:${self:custom.resourcesBaseName}.OutputQueueArn}
    CopiarSFTPRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-copiar-sftp-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${self:provider.stage}-copiar-sftp-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:ListBucket
                    - s3:GetObject
                  Resource: ${cf:${self:custom.resourcesBaseName}.ProcesamientoBucketArn}
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource: ${cf:${self:custom.resourcesBaseName}.SftpServerSecretArn}

stepFunctions:
  stateMachines:
    ProcesamientoStateMachine:
      name: ${self:service}-${self:provider.stage}-procesamiento-state-machine
      definition:
        Comment: Flujo de procesamiento de mensajes
        StartAt: ValidarCliente
        States:
          ValidarCliente:
            Type: Task
            Resource: !GetAtt ValidarCliente.Arn
            Next: ValidarFechas
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: ManejarError
          ValidarFechas:
            Type: Task
            Resource: !GetAtt ValidarFechas.Arn
            Next: ValidarMoneda
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: ManejarError
          ValidarMoneda:
            Type: Task
            Resource: !GetAtt ValidarMoneda.Arn
            Next: GenerarXML
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: ManejarError
          GenerarXML:
            Type: Task
            Resource: !GetAtt GenerarXML.Arn
            Next: ProcesarResultados
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: ManejarError
          ProcesarResultados:
            Type: Parallel
            Branches:
              - StartAt: EnviarResultado
                States:
                  EnviarResultado:
                    Type: Task
                    Resource: !GetAtt EnviarResultado.Arn
                    End: true
              - StartAt: EnviarCorreo
                States:
                  EnviarCorreo:
                    Type: Task
                    Resource: !GetAtt EnviarCorreo.Arn
                    End: true
              - StartAt: CopiarSFTP
                States:
                  CopiarSFTP:
                    Type: Task
                    Resource: !GetAtt CopiarSFTP.Arn
                    End: true
            End: true
            Catch:
              - ErrorEquals: ["States.ALL"]
                Next: ManejarError
          ManejarError:
            Type: Fail
            Cause: "Error no controlado en el flujo de procesamiento."
            Error: "ErrorDesconocido"