Resources:
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-${self:provider.stage}-database-secret
      Description: "Credenciales de la base de datos"
      SecretString: '{"username": "admin", "password": "supersecurepassword", "host": "db.example.com", "dbname": "procesamiento_db"}'

  SftpServerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ${self:service}-${self:provider.stage}-sftp-server-secret
      Description: "Credenciales del servidor SFTP"
      SecretString: '{"username": "admin", "password": "supersecurepassword", "host": "sftp.example.com", "port": 22, "path": "/uploads"}'

Outputs:
  DatabaseSecretArn:
    Description: "ARN del secreto de la base de datos"
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub ${self:service}-${self:provider.stage}-DatabaseSecretArn

  SftpServerSecretArn:
    Description: "ARN del secreto del servidor SFTP"
    Value: !Ref SftpServerSecret
    Export:
      Name: !Sub ${self:service}-${self:provider.stage}-SftpServerSecretArn
