service: confirmation-operations-resources
useDotenv: true

custom:
  stage: ${opt:stage, 'local'}
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  endpointType: REGIONAL
  profile: ${opt:stage, 'dev'}
  stage: ${opt:stage, 'dev'}
  
plugins:
  - serverless-localstack

resources:
  - ${file(sns-sqs.yml)}
  - ${file(s3.yml)}
  - ${file(secrets.yml)}
